In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Sample - Superstore.CSV", encoding = "latin-1")
## encoding term is used to load the dataset if there are any special characters

## with out encoding term the error will be "UTF"(UnicodeDecodeError)

encoding="latin-1" tells Pandas how to translate the bytes in the file into readable characters.

In [3]:
print("Data loaded")

Data loaded

In [4]:
# data rows and columns
df.shape

(9994, 21)

In [5]:
# data info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [6]:
# describe function shows max, min and average for the number columns
#by this we can check the profits or loss of the sales or any numner columns

In [7]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [8]:
# Your Superstore data has 21 columns.
#By default, when you print a table,Pandas shows only a few columns at the start and end, and hides the middle ones with ...
#pd.set_option(...) means “change a Pandas setting”
#"display.max_columns" is the setting name, meaning “the maximum number of columns to show”
#None means “no limit”

#So the whole line says: “Show all columns, don’t hide any.”

In [9]:
pd.set_option("display.max_columns", None)
df.head()
# by above statements we got all the 21 column names
# or another statement (pd.set_option("display.max_columns", 5))

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [10]:
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

## What you want	Statement
#### Show all columns	pd.set_option("display.max_columns", None)
#### Show a specific number	pd.set_option("display.max_columns", 20)
#### Go back to default	pd.reset_option("display.max_columns")
#### Check current value	pd.get_option("display.max_columns")

# Superstore Sales Analysis: Phase 1 Notes

## About the dataset
This dataset contains order records of a retail superstore. It has 9,994 rows
and 21 columns. Each row is one product line within an order, with details
about the customer, location, product, and the sales and profit made.

## Column groups

**Order columns**
- Row ID: unique number for each row
- Order ID: ID of the order
- Order Date: date the order was placed
- Ship Date: date the order was shipped
- Ship Mode: shipping method (e.g. Standard Class,First class, Same day, Second class)

**Customer columns**
- Customer ID: unique ID of the customer
- Customer Name: name of the customer
- Segment: type of customer (Consumer, Corporate, Home Office)

**Location columns**
- Country, State, City, Postal Code: where the order was delivered
- Region: area of the country (West, East, Central, South)

**Product columns**
- Product ID: unique ID of the product
- Category: main product type (Furniture, Office Supplies, Technology)
- Sub-Category: more specific type (e.g. Chairs, Phones)
- Product Name: full name of the product

**Money columns**
- Sales: sales amount of the line
- Quantity: number of units sold
- Discount: discount given (0 to 0.8, i.e. 0% to 80%)
- Profit: profit or loss on the line

## Data types
- **Text:** Order ID, Ship Mode, Customer ID, Customer Name, Segment, Country,
  City, State, Region, Product ID, Category, Sub-Category, Product Name
- **Numbers:** Row ID, Postal Code, Sales, Quantity, Discount, Profit
- **Dates:** Order Date, Ship Date (currently stored as text, to be
  converted in Phase 2)

## Observations from describe()
- Profit ranges from about -6,600 (a loss) to about 8,400.
- Negative profit means the order lost money.
- Most orders are profitable (25th percentile of profit is positive).
- Average discount is about 15.6%, with a maximum of 80%.
- Row ID and Postal Code are identifiers, so their averages are not meaningful.

## Business questions
1. Which region earns the most profit, and which earns the least?
2. Which category and sub-category have the most losses?
3. Do higher discounts lead to lower profit?
4. Who are the top 10 customers by sales?
5. How do sales and profit change over the months and years?